config/routes.rb
Rails.application.routes.draw do

  root 'puzzles#index'

  resources :puzzles, only: [:index, :show]
  get '/check_character', to: 'puzzles#check_character'
  get '/submit_name', to: 'puzzles#submit_toptime'

end

app/models/character.rb
class Character < ActiveRecord::Base

  belongs_to :puzzle
  validates :top, numericality: { only_integer: true }, presence: true
  validates :bottom, numericality: { only_integer: true, greater_than: :top }, presence: true
  validates :left, numericality: { only_integer: true }, presence: true
  validates :right, numericality: { only_integer: true, greater_than: :left }
  validates :name, presence: true

  def check_location(x, y)
    valid = []

    if x.to_i >= self.left && x.to_i <= self.right && y.to_i >= self.top && y.to_i <= self.bottom
      return "found"
    else
      return "tryagain"
    end
  end

end

app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController

  def index
    @puzzles = Puzzle.all
  end

  def show
    @puzzle = Puzzle.find(params[:id])
    @characters = @puzzle.characters
    start_puzzle
  end

  def check_character
    @character = Character.find(params[:c])
    @puzzle = @character.puzzle
    response = {}
    response[:status] = @character.check_location(params[:x], params[:y])
    response[:solve_time] = 0

    if response[:status] == "found"
      found(@character.id)
    end

    if puzzle_solved?
      response[:solve_time] = (Time.now - Time.parse(session[:start_time])).floor
      if @puzzle.toptime == nil
        response[:new_toptime] = "yes"
      elsif response[:solve_time] < @puzzle.toptime
        response[:new_toptime] = "yes"
        @puzzle.update_attribute(:toptime, response[:solve_time]);
      else
        response[:new_toptime] = "no"
      end
    end

    render json: JSON.generate(response)
  end

  def start_puzzle
    session[:remaining] = @puzzle.characters.map(&:id)
    session[:start_time] = Time.now
  end

  def found(character)
    session[:remaining].delete(character)
  end

  def puzzle_solved?
    session[:remaining].empty?
  end

  def submit_toptime
    response = {}
    @puzzle = Puzzle.find(params[:id])
    @puzzle.update_attribute(:topholder, params[:n])
    if @puzzle.topholder == params[:n]
      response[:status] = "saved"
    else
      response[:status] = "failure"
    end

    render json: JSON.generate(response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Where's Waldo and Friends</title>
  <link href='https://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puzzles/index.html.erb
<h1>Where's Waldo</h1>
<h2>Please pick a puzzle</h2>
<div id="index-container">
  <% for puzzle in @puzzles %>
    <%= link_to puzzle_path(puzzle) do %>
    <div class="puzzle-brief">
      <h2><%= puzzle.title %></h2>
      <p><%= puzzle.level %></p>
      <%= link_to( image_tag("thumbs/#{puzzle.image}"), puzzle_path(puzzle)) %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/puzzles/show.html.erb
<h1><%= @puzzle.title %></h1>
<div id="puzzle-div">
  <div id="puzzle-container">
    <%= image_tag(@puzzle.image, id: 'puzzle') %>
    <div id="picker">
      <% for character in @characters %>
        <div id="<%= character.id %>" class="name-button"><%= character.name %></div>
      <% end %>
    </div>
    <div id="complete">
      <h2>Congratalutions!</h2>
      <p>You solved the puzzle in:</p>
      <div id="time"></div>
      <div id="record">
        <p>You've set a new record for this puzzle!</p>
        <p>To save this new record, please submit your name:</p>
        <%= form_tag("#", method: "POST") do %>
          <%= text_field_tag(:username) %>
          <%= submit_tag("Submit", id: "submit") %>
        <% end %>
      </div>
      <div id="tooslow">
        <p>The record for quickest solution is <strong><%= @puzzle.toptime %> seconds</strong> set by <strong><%= @puzzle.topholder %></strong>.</p>
      </div>
    </div>
  </div>
</div>
<div id="character-list-container">
  <div id="character-list">
    <h2>Find:</h2>
    <ul class"character-list">
      <% for character in @characters %>
      <li class="character" id="cl<%= character.id %>"><div class="name"><%= character.name %></div><%= image_tag("characters/#{character.name}.jpg") %>
      </li>
    <% end %>
    </ul>
    <div id="back"><%= link_to("Back", puzzles_path) %></div>
  </div>
</div>